alter session set "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER gornostay IDENTIFIED BY qwer
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "CONNECT" TO gornostay ;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO gornostay ;
GRANT CREATE TABLE TO gornostay ;
GRANT CREATE PROCEDURE TO gornostay ;
GRANT CREATE VIEW TO gornostay ;
GRANT CREATE SESSION TO gornostay ;
Grant Alter Table to gornostay;


-- QUOTAS
ALTER USER GORNOSTAY QUOTA UNLIMITED ON USERS;